services:
  backend:
    build: ./backend
    container_name: smart_task_assistant_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15
    container_name: smart_task_assistant_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: smart_task_assistant_rabbitmq
    ports:
      - "${RABBITMQ_PORT_1}:${RABBITMQ_PORT_1}"
      - "${RABBITMQ_PORT_2}:${RABBITMQ_PORT_2}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  worker:
    build: ./backend
    container_name: smart_task_assistant_worker
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
